// const fs = require("fs");
//for restaurant
const image = [
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "h7",
  "h8",
  "h9",
  "h10",
  "h11",
  "h12",
  "h13",
  "h14",
  "h15",
  "h16",
  "h17",
  "h18",
  "h19",
  "h20",
];
const restaurantNames = [
  "The Royal Spoon",
  "Spice Symphony",
  "Urban Tandoor",
  "Bella Italia",
  "Sushi Zen",
  "Curry & Co.",
  "The Green Bowl",
  "Flame & Grill",
  "Masala Junction",
  "The Continental",
  "Tandoori Nights",
  "Zen Garden",
  "Bombay Biryani Hub",
  "The Kebab Factory",
  "Café de Paris",
  "The Breakfast Club",
  "Dosa District",
  "Grill House",
  "The Spice Route",
  "Café Nirvana",
];
const foodTypes = [
  "Indian",
  "Chinese",
  "Italian",
  "Japanese",
  "Thai",
  "Mexican",
  "American",
  "French",
  "Mediterranean",
  "Korean",
  "Vietnamese",
  "Lebanese",
  "South Indian",
  "North Indian",
  "Mughlai",
  "BBQ",
  "Seafood",
  "Vegan",
  "Fusion",
  "Continental",
];
const mumbaiLocations = [
  "Andheri",
  "Bandra",
  "Borivali",
  "Colaba",
  "Dadar",
  "Goregaon",
  "Juhu",
  "Kurla",
  "Malad",
  "Matunga",
  "Powai",
  "Santacruz",
  "Sion",
  "Vile Parle",
  "Vasai",
  "Versova",
  "Chembur",
  "Worli",
  "Marine Lines",
  "Churchgate",
];
const filterIdsOfRestaurants = [
  "cuisineFilterRest",
  "locationFilterRest",
  "alcoholFilterRest",
  "priceFilterRest",
  "distanceFilterRest",
];
//for delivery
const filterIdsOfDelivery = [
  "cuisineFilterDeli",
  "categoryFilterDeli",
  "vegFilterDeli",
  "ratingFilterDeli",
  "priceFilterDeli",
];
const foodNames = [
  "Paneer Tikka",
  "Chicken Biryani",
  "Margherita Pizza",
  "Butter Chicken",
  "Veg Hakka Noodles",
  "Mutton Rogan Josh",
  "Masala Dosa",
  "Tandoori Chicken",
  "Pav Bhaji",
  "Fish Curry",
  "Chole Bhature",
  "Egg Fried Rice",
  "Cheese Burst Pizza",
  "Dal Makhani",
  "Chicken Shawarma",
  "Veg Manchurian",
  "Kathi Roll",
  "Idli Sambar",
  "Chicken Tikka Wrap",
  "Veg Pulao",
  "Momos",
  "Keema Pav",
  "Falafel Bowl",
  "Chicken Korma",
  "Rajma Chawal",
  "Masala Chai",
  "Cold Coffee",
  "Fresh Lime Soda",
  "Mango Lassi",
  "Green Tea",
  "Cappuccino",
  "Iced Americano",
  "Strawberry Milkshake",
  "Watermelon Juice",
  "Hot Chocolate",
  "Virgin Mojito",
  "Peach Iced Tea",
  "Coconut Water",
  "Onion Rings",
  "Grilled Sandwich",
  "Veg Hot Dog",
  "Chicken Hot Dog",
  "Pizza Slice",
  "Paneer Tikka Roll",
  "Chicken Tikka Roll",
  "Veg Momos",
  "Chicken Momos",
  "Garlic Bread",
  "Cheesy Nachos",
  "Veg Puff",
  "Coca-Cola",
  "Pepsi",
  "Sprite",
  "Mountain Dew",
  "Fanta",
  "Thums Up",
  "Limca",
  "7UP",
  "Iced Tea",
  "Blue Lagoon",
  "Strawberry Shake",
];

const cuisineTypes = [
  "North Indian",
  "Hyderabadi",
  "Italian",
  "Punjabi",
  "Chinese",
  "Kashmiri",
  "South Indian",
  "Mughlai",
  "Mumbai Street",
  "Goan",
  "Delhi Street",
  "Indian",
  "Cafe",
  "Asian",
  "American",
  "Fresh",
  "European",
  "Mocktail",
  "Natural",
  "Fast Food",
  "Soft Drink",
  "Shake",
];
const categories = ["Main Course", "Drink", "Fast Food", "Cold Drink"];
const isVeg = ["yes", "No"];
const ratings = [3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9];
const menuImages = ["m1", "m2", "m3", "m4"];
