//restaurant data
const restaurant = [
  {
    image: "h18",
    rest_name: "Flame & Grill",
    food_type: "Mediterranean",
    price_for_two: 2225,
    location: "Sion",
    distance_from_customer_house: "29.13 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "21:00 PM",
  },
  {
    image: "h12",
    rest_name: "Masala Junction",
    food_type: "Continental",
    price_for_two: 1612,
    location: "Matunga",
    distance_from_customer_house: "19.80 km",
    alcohol: "No",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h17",
    rest_name: "Spice Symphony",
    food_type: "Korean",
    price_for_two: 682,
    location: "Kurla",
    distance_from_customer_house: "21.61 km",
    alcohol: "No",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "21:00 PM",
  },
  {
    image: "h14",
    rest_name: "The Royal Spoon",
    food_type: "South Indian",
    price_for_two: 2014,
    location: "Matunga",
    distance_from_customer_house: "6.39 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h1",
    rest_name: "Grill House",
    food_type: "Thai",
    price_for_two: 2012,
    location: "Goregaon",
    distance_from_customer_house: "4.84 km",
    alcohol: "Yes",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "21:00 PM",
  },
  {
    image: "h6",
    rest_name: "Tandoori Nights",
    food_type: "Continental",
    price_for_two: 2465,
    location: "Kurla",
    distance_from_customer_house: "15.91 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h20",
    rest_name: "Zen Garden",
    food_type: "BBQ",
    price_for_two: 2286,
    location: "Malad",
    distance_from_customer_house: "10.43 km",
    alcohol: "No",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h18",
    rest_name: "The Royal Spoon",
    food_type: "North Indian",
    price_for_two: 2141,
    location: "Powai",
    distance_from_customer_house: "29.44 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h12",
    rest_name: "Zen Garden",
    food_type: "Mediterranean",
    price_for_two: 303,
    location: "Chembur",
    distance_from_customer_house: "1.85 km",
    alcohol: "Yes",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h6",
    rest_name: "Spice Symphony",
    food_type: "Mediterranean",
    price_for_two: 2338,
    location: "Santacruz",
    distance_from_customer_house: "5.31 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h17",
    rest_name: "Masala Junction",
    food_type: "Italian",
    price_for_two: 1622,
    location: "Dadar",
    distance_from_customer_house: "12.49 km",
    alcohol: "Yes",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h6",
    rest_name: "The Spice Route",
    food_type: "Thai",
    price_for_two: 1207,
    location: "Santacruz",
    distance_from_customer_house: "18.19 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h3",
    rest_name: "Grill House",
    food_type: "American",
    price_for_two: 332,
    location: "Versova",
    distance_from_customer_house: "17.43 km",
    alcohol: "Yes",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h6",
    rest_name: "Grill House",
    food_type: "American",
    price_for_two: 587,
    location: "Powai",
    distance_from_customer_house: "25.22 km",
    alcohol: "No",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h1",
    rest_name: "Sushi Zen",
    food_type: "Korean",
    price_for_two: 433,
    location: "Santacruz",
    distance_from_customer_house: "8.45 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h6",
    rest_name: "The Spice Route",
    food_type: "BBQ",
    price_for_two: 1598,
    location: "Colaba",
    distance_from_customer_house: "4.27 km",
    alcohol: "No",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h5",
    rest_name: "The Continental",
    food_type: "South Indian",
    price_for_two: 1270,
    location: "Malad",
    distance_from_customer_house: "5.98 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h1",
    rest_name: "Masala Junction",
    food_type: "Thai",
    price_for_two: 1243,
    location: "Andheri",
    distance_from_customer_house: "18.85 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h12",
    rest_name: "The Continental",
    food_type: "Vegan",
    price_for_two: 286,
    location: "Santacruz",
    distance_from_customer_house: "6.84 km",
    alcohol: "No",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h15",
    rest_name: "Zen Garden",
    food_type: "South Indian",
    price_for_two: 107,
    location: "Malad",
    distance_from_customer_house: "18.62 km",
    alcohol: "Yes",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h15",
    rest_name: "Urban Tandoor",
    food_type: "Mughlai",
    price_for_two: 1534,
    location: "Bandra",
    distance_from_customer_house: "7.41 km",
    alcohol: "No",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h13",
    rest_name: "The Continental",
    food_type: "Vietnamese",
    price_for_two: 2324,
    location: "Worli",
    distance_from_customer_house: "22.59 km",
    alcohol: "No",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h11",
    rest_name: "Café Nirvana",
    food_type: "North Indian",
    price_for_two: 2201,
    location: "Bandra",
    distance_from_customer_house: "24.05 km",
    alcohol: "No",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h5",
    rest_name: "Masala Junction",
    food_type: "American",
    price_for_two: 428,
    location: "Colaba",
    distance_from_customer_house: "22.33 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h9",
    rest_name: "Urban Tandoor",
    food_type: "Lebanese",
    price_for_two: 1284,
    location: "Malad",
    distance_from_customer_house: "5.53 km",
    alcohol: "Yes",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "21:00 PM",
  },
  {
    image: "h11",
    rest_name: "Spice Symphony",
    food_type: "Seafood",
    price_for_two: 1415,
    location: "Vile Parle",
    distance_from_customer_house: "14.36 km",
    alcohol: "Yes",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h6",
    rest_name: "Masala Junction",
    food_type: "Mexican",
    price_for_two: 940,
    location: "Sion",
    distance_from_customer_house: "6.15 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h16",
    rest_name: "Grill House",
    food_type: "Chinese",
    price_for_two: 1461,
    location: "Powai",
    distance_from_customer_house: "13.56 km",
    alcohol: "Yes",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h5",
    rest_name: "Café Nirvana",
    food_type: "BBQ",
    price_for_two: 1555,
    location: "Kurla",
    distance_from_customer_house: "7.50 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h4",
    rest_name: "The Spice Route",
    food_type: "Continental",
    price_for_two: 1833,
    location: "Versova",
    distance_from_customer_house: "25.57 km",
    alcohol: "Yes",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h17",
    rest_name: "Masala Junction",
    food_type: "Japanese",
    price_for_two: 430,
    location: "Matunga",
    distance_from_customer_house: "18.90 km",
    alcohol: "No",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "21:00 PM",
  },
  {
    image: "h1",
    rest_name: "Bombay Biryani Hub",
    food_type: "Lebanese",
    price_for_two: 1810,
    location: "Malad",
    distance_from_customer_house: "6.59 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "21:00 PM",
  },
  {
    image: "h5",
    rest_name: "Urban Tandoor",
    food_type: "Italian",
    price_for_two: 1791,
    location: "Vile Parle",
    distance_from_customer_house: "18.68 km",
    alcohol: "No",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h19",
    rest_name: "The Kebab Factory",
    food_type: "Vietnamese",
    price_for_two: 660,
    location: "Versova",
    distance_from_customer_house: "15.72 km",
    alcohol: "Yes",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h18",
    rest_name: "Curry & Co.",
    food_type: "North Indian",
    price_for_two: 1502,
    location: "Santacruz",
    distance_from_customer_house: "12.77 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h8",
    rest_name: "The Spice Route",
    food_type: "South Indian",
    price_for_two: 1700,
    location: "Dadar",
    distance_from_customer_house: "27.37 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h4",
    rest_name: "Masala Junction",
    food_type: "Fusion",
    price_for_two: 1809,
    location: "Churchgate",
    distance_from_customer_house: "10.62 km",
    alcohol: "No",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h16",
    rest_name: "Café Nirvana",
    food_type: "Lebanese",
    price_for_two: 853,
    location: "Vile Parle",
    distance_from_customer_house: "13.75 km",
    alcohol: "Yes",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "21:00 PM",
  },
  {
    image: "h7",
    rest_name: "Tandoori Nights",
    food_type: "American",
    price_for_two: 819,
    location: "Sion",
    distance_from_customer_house: "9.30 km",
    alcohol: "No",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "21:00 PM",
  },
  {
    image: "h8",
    rest_name: "Dosa District",
    food_type: "Japanese",
    price_for_two: 2370,
    location: "Churchgate",
    distance_from_customer_house: "21.31 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h5",
    rest_name: "Dosa District",
    food_type: "Korean",
    price_for_two: 1626,
    location: "Colaba",
    distance_from_customer_house: "9.88 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h14",
    rest_name: "The Green Bowl",
    food_type: "Fusion",
    price_for_two: 130,
    location: "Vasai",
    distance_from_customer_house: "4.99 km",
    alcohol: "No",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h13",
    rest_name: "Urban Tandoor",
    food_type: "Chinese",
    price_for_two: 510,
    location: "Juhu",
    distance_from_customer_house: "11.30 km",
    alcohol: "No",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h14",
    rest_name: "Tandoori Nights",
    food_type: "BBQ",
    price_for_two: 2239,
    location: "Powai",
    distance_from_customer_house: "1.06 km",
    alcohol: "Yes",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h18",
    rest_name: "Café de Paris",
    food_type: "Fusion",
    price_for_two: 1464,
    location: "Dadar",
    distance_from_customer_house: "0.87 km",
    alcohol: "Yes",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h20",
    rest_name: "The Green Bowl",
    food_type: "Continental",
    price_for_two: 672,
    location: "Vile Parle",
    distance_from_customer_house: "19.49 km",
    alcohol: "Yes",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h9",
    rest_name: "The Green Bowl",
    food_type: "Continental",
    price_for_two: 490,
    location: "Dadar",
    distance_from_customer_house: "4.53 km",
    alcohol: "Yes",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h1",
    rest_name: "Dosa District",
    food_type: "South Indian",
    price_for_two: 1109,
    location: "Andheri",
    distance_from_customer_house: "18.28 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h10",
    rest_name: "Urban Tandoor",
    food_type: "Thai",
    price_for_two: 1118,
    location: "Marine Lines",
    distance_from_customer_house: "13.02 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h18",
    rest_name: "The Green Bowl",
    food_type: "Japanese",
    price_for_two: 1458,
    location: "Versova",
    distance_from_customer_house: "6.42 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "21:00 PM",
  },
  {
    image: "h1",
    rest_name: "Café Nirvana",
    food_type: "Italian",
    price_for_two: 2414,
    location: "Borivali",
    distance_from_customer_house: "1.94 km",
    alcohol: "No",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h7",
    rest_name: "Zen Garden",
    food_type: "Korean",
    price_for_two: 1987,
    location: "Andheri",
    distance_from_customer_house: "13.96 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h14",
    rest_name: "Dosa District",
    food_type: "Vietnamese",
    price_for_two: 1579,
    location: "Andheri",
    distance_from_customer_house: "21.94 km",
    alcohol: "No",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h10",
    rest_name: "Masala Junction",
    food_type: "Thai",
    price_for_two: 139,
    location: "Malad",
    distance_from_customer_house: "28.19 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h4",
    rest_name: "The Spice Route",
    food_type: "French",
    price_for_two: 1685,
    location: "Chembur",
    distance_from_customer_house: "24.91 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h18",
    rest_name: "The Continental",
    food_type: "Italian",
    price_for_two: 2052,
    location: "Powai",
    distance_from_customer_house: "22.36 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h19",
    rest_name: "Spice Symphony",
    food_type: "Mediterranean",
    price_for_two: 358,
    location: "Bandra",
    distance_from_customer_house: "3.69 km",
    alcohol: "No",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h5",
    rest_name: "Sushi Zen",
    food_type: "Korean",
    price_for_two: 1531,
    location: "Santacruz",
    distance_from_customer_house: "7.97 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h3",
    rest_name: "Urban Tandoor",
    food_type: "Vegan",
    price_for_two: 2328,
    location: "Versova",
    distance_from_customer_house: "26.49 km",
    alcohol: "No",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h6",
    rest_name: "Zen Garden",
    food_type: "Mediterranean",
    price_for_two: 359,
    location: "Chembur",
    distance_from_customer_house: "6.02 km",
    alcohol: "Yes",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h8",
    rest_name: "Curry & Co.",
    food_type: "Fusion",
    price_for_two: 1425,
    location: "Marine Lines",
    distance_from_customer_house: "29.20 km",
    alcohol: "No",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h17",
    rest_name: "Grill House",
    food_type: "Japanese",
    price_for_two: 2337,
    location: "Vile Parle",
    distance_from_customer_house: "13.28 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h1",
    rest_name: "The Spice Route",
    food_type: "BBQ",
    price_for_two: 1916,
    location: "Vile Parle",
    distance_from_customer_house: "28.21 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h12",
    rest_name: "Zen Garden",
    food_type: "Mediterranean",
    price_for_two: 1118,
    location: "Goregaon",
    distance_from_customer_house: "8.67 km",
    alcohol: "Yes",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h17",
    rest_name: "Café de Paris",
    food_type: "North Indian",
    price_for_two: 1235,
    location: "Andheri",
    distance_from_customer_house: "15.88 km",
    alcohol: "No",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h5",
    rest_name: "The Spice Route",
    food_type: "Chinese",
    price_for_two: 1788,
    location: "Powai",
    distance_from_customer_house: "11.38 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h1",
    rest_name: "Tandoori Nights",
    food_type: "Thai",
    price_for_two: 1898,
    location: "Andheri",
    distance_from_customer_house: "0.07 km",
    alcohol: "No",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h5",
    rest_name: "Bombay Biryani Hub",
    food_type: "Thai",
    price_for_two: 1554,
    location: "Kurla",
    distance_from_customer_house: "15.51 km",
    alcohol: "Yes",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h3",
    rest_name: "Urban Tandoor",
    food_type: "French",
    price_for_two: 1513,
    location: "Juhu",
    distance_from_customer_house: "20.16 km",
    alcohol: "No",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "21:00 PM",
  },
  {
    image: "h17",
    rest_name: "The Spice Route",
    food_type: "Vietnamese",
    price_for_two: 785,
    location: "Churchgate",
    distance_from_customer_house: "5.43 km",
    alcohol: "No",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h4",
    rest_name: "The Royal Spoon",
    food_type: "Chinese",
    price_for_two: 2007,
    location: "Juhu",
    distance_from_customer_house: "25.41 km",
    alcohol: "Yes",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h18",
    rest_name: "Sushi Zen",
    food_type: "Thai",
    price_for_two: 1524,
    location: "Vasai",
    distance_from_customer_house: "4.85 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "21:00 PM",
  },
  {
    image: "h1",
    rest_name: "The Royal Spoon",
    food_type: "Vietnamese",
    price_for_two: 1590,
    location: "Juhu",
    distance_from_customer_house: "7.19 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h4",
    rest_name: "The Breakfast Club",
    food_type: "North Indian",
    price_for_two: 677,
    location: "Vile Parle",
    distance_from_customer_house: "22.41 km",
    alcohol: "No",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h12",
    rest_name: "Bombay Biryani Hub",
    food_type: "Lebanese",
    price_for_two: 526,
    location: "Versova",
    distance_from_customer_house: "0.10 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h12",
    rest_name: "The Continental",
    food_type: "Continental",
    price_for_two: 1976,
    location: "Sion",
    distance_from_customer_house: "20.60 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "21:00 PM",
  },
  {
    image: "h19",
    rest_name: "Spice Symphony",
    food_type: "Seafood",
    price_for_two: 323,
    location: "Goregaon",
    distance_from_customer_house: "8.98 km",
    alcohol: "Yes",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h4",
    rest_name: "Urban Tandoor",
    food_type: "Continental",
    price_for_two: 1571,
    location: "Andheri",
    distance_from_customer_house: "7.68 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h5",
    rest_name: "Curry & Co.",
    food_type: "Mughlai",
    price_for_two: 219,
    location: "Malad",
    distance_from_customer_house: "2.65 km",
    alcohol: "Yes",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h15",
    rest_name: "The Breakfast Club",
    food_type: "French",
    price_for_two: 1064,
    location: "Goregaon",
    distance_from_customer_house: "16.32 km",
    alcohol: "Yes",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h20",
    rest_name: "Flame & Grill",
    food_type: "Thai",
    price_for_two: 844,
    location: "Marine Lines",
    distance_from_customer_house: "10.94 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h16",
    rest_name: "Café Nirvana",
    food_type: "French",
    price_for_two: 530,
    location: "Sion",
    distance_from_customer_house: "16.99 km",
    alcohol: "No",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h16",
    rest_name: "Bombay Biryani Hub",
    food_type: "Mediterranean",
    price_for_two: 868,
    location: "Sion",
    distance_from_customer_house: "0.01 km",
    alcohol: "No",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h8",
    rest_name: "Bella Italia",
    food_type: "Thai",
    price_for_two: 910,
    location: "Matunga",
    distance_from_customer_house: "27.34 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "21:00 PM",
  },
  {
    image: "h2",
    rest_name: "Flame & Grill",
    food_type: "North Indian",
    price_for_two: 256,
    location: "Marine Lines",
    distance_from_customer_house: "16.86 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h5",
    rest_name: "Flame & Grill",
    food_type: "Mughlai",
    price_for_two: 419,
    location: "Borivali",
    distance_from_customer_house: "6.83 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h2",
    rest_name: "Spice Symphony",
    food_type: "Continental",
    price_for_two: 646,
    location: "Sion",
    distance_from_customer_house: "5.35 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h5",
    rest_name: "Flame & Grill",
    food_type: "American",
    price_for_two: 2476,
    location: "Santacruz",
    distance_from_customer_house: "28.70 km",
    alcohol: "Yes",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h8",
    rest_name: "Grill House",
    food_type: "Continental",
    price_for_two: 1968,
    location: "Andheri",
    distance_from_customer_house: "2.52 km",
    alcohol: "Yes",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h16",
    rest_name: "The Breakfast Club",
    food_type: "Seafood",
    price_for_two: 1642,
    location: "Kurla",
    distance_from_customer_house: "8.44 km",
    alcohol: "No",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h1",
    rest_name: "The Spice Route",
    food_type: "Thai",
    price_for_two: 1949,
    location: "Sion",
    distance_from_customer_house: "25.06 km",
    alcohol: "No",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h18",
    rest_name: "Dosa District",
    food_type: "Mexican",
    price_for_two: 711,
    location: "Versova",
    distance_from_customer_house: "14.16 km",
    alcohol: "No",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h16",
    rest_name: "Grill House",
    food_type: "French",
    price_for_two: 2098,
    location: "Borivali",
    distance_from_customer_house: "16.83 km",
    alcohol: "Yes",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h1",
    rest_name: "Grill House",
    food_type: "BBQ",
    price_for_two: 271,
    location: "Andheri",
    distance_from_customer_house: "2.91 km",
    alcohol: "Yes",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "24:00 PM",
  },
  {
    image: "h6",
    rest_name: "Grill House",
    food_type: "Korean",
    price_for_two: 1602,
    location: "Dadar",
    distance_from_customer_house: "26.39 km",
    alcohol: "No",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "21:00 PM",
  },
  {
    image: "h13",
    rest_name: "Urban Tandoor",
    food_type: "Mexican",
    price_for_two: 875,
    location: "Powai",
    distance_from_customer_house: "22.61 km",
    alcohol: "Yes",
    restaurant_open_time: "11:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h2",
    rest_name: "Zen Garden",
    food_type: "Continental",
    price_for_two: 1875,
    location: "Juhu",
    distance_from_customer_house: "2.97 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "23:00 PM",
  },
  {
    image: "h7",
    rest_name: "The Breakfast Club",
    food_type: "Vietnamese",
    price_for_two: 1320,
    location: "Dadar",
    distance_from_customer_house: "28.69 km",
    alcohol: "Yes",
    restaurant_open_time: "8:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h4",
    rest_name: "The Spice Route",
    food_type: "BBQ",
    price_for_two: 705,
    location: "Bandra",
    distance_from_customer_house: "7.57 km",
    alcohol: "Yes",
    restaurant_open_time: "10:00 AM",
    restaurant_close_time: "22:00 PM",
  },
  {
    image: "h12",
    rest_name: "Flame & Grill",
    food_type: "Vietnamese",
    price_for_two: 998,
    location: "Churchgate",
    distance_from_customer_house: "29.55 km",
    alcohol: "No",
    restaurant_open_time: "9:00 AM",
    restaurant_close_time: "23:00 PM",
  },
];

//delivery data
const deliveryItems = [
  //main course
  {
    name: "Paneer Tikka",
    category: "Main Course",
    cuisine_type: "North Indian",
    price: 249,
    is_veg: true,
    rating: 4.5,
    prep_time: 20,
    image: "f1",
  },
  {
    name: "Chicken Biryani",
    category: "Main Course",
    cuisine_type: "Hyderabadi",
    price: 299,
    is_veg: false,
    rating: 4.7,
    prep_time: 25,
    image: "f2",
  },
  {
    name: "Margherita Pizza",
    category: "Main Course",
    cuisine_type: "Italian",
    price: 199,
    is_veg: true,
    rating: 4.2,
    prep_time: 18,
    image: "f3",
  },
  {
    name: "Butter Chicken",
    category: "Main Course",
    cuisine_type: "Punjabi",
    price: 289,
    is_veg: false,
    rating: 4.6,
    prep_time: 22,
    image: "f4",
  },
  {
    name: "Veg Hakka Noodles",
    category: "Main Course",
    cuisine_type: "Chinese",
    price: 179,
    is_veg: true,
    rating: 4.1,
    prep_time: 15,
    image: "f5",
  },

  {
    name: "Mutton Rogan Josh",
    category: "Main Course",
    cuisine_type: "Kashmiri",
    price: 349,
    is_veg: false,
    rating: 4.8,
    prep_time: 30,
    image: "f6",
  },
  {
    name: "Masala Dosa",
    category: "Main Course",
    cuisine_type: "South Indian",
    price: 149,
    is_veg: true,
    rating: 4.3,
    prep_time: 12,
    image: "f7",
  },
  {
    name: "Tandoori Chicken",
    category: "Main Course",
    cuisine_type: "Mughlai",
    price: 299,
    is_veg: false,
    rating: 4.5,
    prep_time: 28,
    image: "f8",
  },
  {
    name: "Pav Bhaji",
    category: "Main Course",
    cuisine_type: "Mumbai Street",
    price: 129,
    is_veg: true,
    rating: 4.4,
    prep_time: 14,
    image: "f9",
  },
  {
    name: "Fish Curry",
    category: "Main Course",
    cuisine_type: "Goan",
    price: 279,
    is_veg: false,
    rating: 4.6,
    prep_time: 26,
    image: "f10",
  },

  {
    name: "Chole Bhature",
    category: "Main Course",
    cuisine_type: "Delhi Street",
    price: 159,
    is_veg: true,
    rating: 4.2,
    prep_time: 16,
    image: "f11",
  },
  {
    name: "Egg Fried Rice",
    category: "Main Course",
    cuisine_type: "Chinese",
    price: 189,
    is_veg: false,
    rating: 4.1,
    prep_time: 15,
    image: "f12",
  },
  {
    name: "Cheese Burst Pizza",
    category: "Main Course",
    cuisine_type: "Italian",
    price: 249,
    is_veg: true,
    rating: 4.3,
    prep_time: 20,
    image: "f13",
  },
  {
    name: "Dal Makhani",
    category: "Main Course",
    cuisine_type: "Punjabi",
    price: 199,
    is_veg: true,
    rating: 4.5,
    prep_time: 22,
    image: "f14",
  },
  {
    name: "Chicken Shawarma",
    category: "Main Course",
    cuisine_type: "Middle Eastern",
    price: 229,
    is_veg: false,
    rating: 4.4,
    prep_time: 18,
    image: "f15",
  },

  {
    name: "Veg Manchurian",
    category: "Main Course",
    cuisine_type: "Indo-Chinese",
    price: 169,
    is_veg: true,
    rating: 4.2,
    prep_time: 17,
    image: "f16",
  },
  {
    name: "Kathi Roll",
    category: "Main Course",
    cuisine_type: "Kolkata Street",
    price: 149,
    is_veg: false,
    rating: 4.3,
    prep_time: 14,
    image: "f17",
  },
  {
    name: "Idli Sambar",
    category: "Main Course",
    cuisine_type: "South Indian",
    price: 129,
    is_veg: true,
    rating: 4.1,
    prep_time: 10,
    image: "f18",
  },
  {
    name: "Chicken Tikka Wrap",
    category: "Main Course",
    cuisine_type: "Fusion",
    price: 199,
    is_veg: false,
    rating: 4.5,
    prep_time: 16,
    image: "f19",
  },
  {
    name: "Veg Pulao",
    category: "Main Course",
    cuisine_type: "North Indian",
    price: 159,
    is_veg: true,
    rating: 4.2,
    prep_time: 15,
    image: "f20",
  },

  {
    name: "Momos",
    category: "Main Course",
    cuisine_type: "Tibetan",
    price: 139,
    is_veg: true,
    rating: 4.3,
    prep_time: 12,
    image: "f21",
  },
  {
    name: "Keema Pav",
    category: "Main Course",
    cuisine_type: "Mumbai Street",
    price: 179,
    is_veg: false,
    rating: 4.4,
    prep_time: 14,
    image: "f22",
  },
  {
    name: "Falafel Bowl",
    category: "Main Course",
    cuisine_type: "Mediterranean",
    price: 219,
    is_veg: true,
    rating: 4.5,
    prep_time: 20,
    image: "f23",
  },
  {
    name: "Chicken Korma",
    category: "Main Course",
    cuisine_type: "Mughlai",
    price: 289,
    is_veg: false,
    rating: 4.6,
    prep_time: 25,
    image: "f24",
  },
  {
    name: "Rajma Chawal",
    category: "Main Course",
    cuisine_type: "North Indian",
    price: 149,
    is_veg: true,
    rating: 4.2,
    prep_time: 18,
    image: "f25",
  },
  //drinks
  {
    name: "Masala Chai",
    category: "Drink",
    cuisine_type: "Indian",
    price: 49,
    is_veg: true,
    rating: 4.6,
    prep_time: 5,
    image: "f26",
  },
  {
    name: "Cold Coffee",
    category: "Drink",
    cuisine_type: "Cafe",
    price: 99,
    is_veg: true,
    rating: 4.4,
    prep_time: 6,
    image: "f27",
  },
  {
    name: "Fresh Lime Soda",
    category: "Drink",
    cuisine_type: "Indian",
    price: 69,
    is_veg: true,
    rating: 4.3,
    prep_time: 4,
    image: "f28",
  },
  {
    name: "Mango Lassi",
    category: "Drink",
    cuisine_type: "Punjabi",
    price: 89,
    is_veg: true,
    rating: 4.5,
    prep_time: 5,
    image: "f29",
  },
  {
    name: "Green Tea",
    category: "Drink",
    cuisine_type: "Asian",
    price: 59,
    is_veg: true,
    rating: 4.2,
    prep_time: 3,
    image: "f30",
  },

  {
    name: "Cappuccino",
    category: "Drink",
    cuisine_type: "Italian",
    price: 129,
    is_veg: true,
    rating: 4.6,
    prep_time: 7,
    image: "f31",
  },
  {
    name: "Iced Americano",
    category: "Drink",
    cuisine_type: "American",
    price: 119,
    is_veg: true,
    rating: 4.4,
    prep_time: 6,
    image: "f32",
  },
  {
    name: "Strawberry Milkshake",
    category: "Drink",
    cuisine_type: "Cafe",
    price: 139,
    is_veg: true,
    rating: 4.5,
    prep_time: 6,
    image: "f33",
  },
  {
    name: "Watermelon Juice",
    category: "Drink",
    cuisine_type: "Fresh",
    price: 79,
    is_veg: true,
    rating: 4.3,
    prep_time: 5,
    image: "f34",
  },
  {
    name: "Hot Chocolate",
    category: "Drink",
    cuisine_type: "European",
    price: 149,
    is_veg: true,
    rating: 4.6,
    prep_time: 7,
    image: "f35",
  },

  {
    name: "Virgin Mojito",
    category: "Drink",
    cuisine_type: "Mocktail",
    price: 129,
    is_veg: true,
    rating: 4.4,
    prep_time: 5,
    image: "f36",
  },
  {
    name: "Peach Iced Tea",
    category: "Drink",
    cuisine_type: "Cafe",
    price: 109,
    is_veg: true,
    rating: 4.3,
    prep_time: 5,
    image: "f37",
  },
  {
    name: "Coconut Water",
    category: "Drink",
    cuisine_type: "Natural",
    price: 59,
    is_veg: true,
    rating: 4.2,
    prep_time: 2,
    image: "f38",
  },
  //fastfood
  {
    name: "Onion Rings",
    category: "Fast Food",
    cuisine_type: "Fast Food",
    price: 109,
    is_veg: true,
    rating: 4.3,
    prep_time: 8,
    image: "f39",
  },
  {
    name: "Grilled Sandwich",
    category: "Fast Food",
    cuisine_type: "Fast Food",
    price: 129,
    is_veg: true,
    rating: 4.2,
    prep_time: 9,
    image: "f40",
  },
  {
    name: "Veg Hot Dog",
    category: "Fast Food",
    cuisine_type: "Fast Food",
    price: 139,
    is_veg: true,
    rating: 4.1,
    prep_time: 10,
    image: "f41",
  },
  {
    name: "Chicken Hot Dog",
    category: "Fast Food",
    cuisine_type: "Fast Food",
    price: 159,
    is_veg: false,
    rating: 4.3,
    prep_time: 11,
    image: "f42",
  },
  {
    name: "Pizza Slice",
    category: "Fast Food",
    cuisine_type: "Fast Food",
    price: 99,
    is_veg: true,
    rating: 4.2,
    prep_time: 7,
    image: "f43",
  },

  {
    name: "Paneer Tikka Roll",
    category: "Fast Food",
    cuisine_type: "Fast Food",
    price: 149,
    is_veg: true,
    rating: 4.4,
    prep_time: 12,
    image: "f44",
  },
  {
    name: "Chicken Tikka Roll",
    category: "Fast Food",
    cuisine_type: "Fast Food",
    price: 169,
    is_veg: false,
    rating: 4.5,
    prep_time: 13,
    image: "f45",
  },
  {
    name: "Veg Momos",
    category: "Fast Food",
    cuisine_type: "Fast Food",
    price: 119,
    is_veg: true,
    rating: 4.3,
    prep_time: 10,
    image: "f46",
  },
  {
    name: "Chicken Momos",
    category: "Fast Food",
    cuisine_type: "Fast Food",
    price: 139,
    is_veg: false,
    rating: 4.4,
    prep_time: 11,
    image: "f47",
  },
  {
    name: "Garlic Bread",
    category: "Fast Food",
    cuisine_type: "Fast Food",
    price: 99,
    is_veg: true,
    rating: 4.2,
    prep_time: 6,
    image: "f48",
  },

  {
    name: "Cheesy Nachos",
    category: "Fast Food",
    cuisine_type: "Fast Food",
    price: 129,
    is_veg: true,
    rating: 4.3,
    prep_time: 8,
    image: "f49",
  },
  {
    name: "Veg Puff",
    category: "Fast Food",
    cuisine_type: "Fast Food",
    price: 89,
    is_veg: true,
    rating: 4.1,
    prep_time: 7,
    image: "f50",
  },

  //coldrink
  {
    name: "Coca-Cola",
    category: "Cold Drink",
    cuisine_type: "Soft Drink",
    price: 49,
    is_veg: true,
    rating: 4.5,
    prep_time: 2,
    image: "f51",
  },
  {
    name: "Pepsi",
    category: "Cold Drink",
    cuisine_type: "Soft Drink",
    price: 49,
    is_veg: true,
    rating: 4.4,
    prep_time: 2,
    image: "f52",
  },
  {
    name: "Sprite",
    category: "Cold Drink",
    cuisine_type: "Soft Drink",
    price: 49,
    is_veg: true,
    rating: 4.3,
    prep_time: 2,
    image: "f53",
  },
  {
    name: "Mountain Dew",
    category: "Cold Drink",
    cuisine_type: "Soft Drink",
    price: 49,
    is_veg: true,
    rating: 4.2,
    prep_time: 2,
    image: "f54",
  },
  {
    name: "Fanta",
    category: "Cold Drink",
    cuisine_type: "Soft Drink",
    price: 49,
    is_veg: true,
    rating: 4.3,
    prep_time: 2,
    image: "f55",
  },
  {
    name: "Thums Up",
    category: "Cold Drink",
    cuisine_type: "Soft Drink",
    price: 49,
    is_veg: true,
    rating: 4.4,
    prep_time: 2,
    image: "f56",
  },
  {
    name: "Limca",
    category: "Cold Drink",
    cuisine_type: "Soft Drink",
    price: 49,
    is_veg: true,
    rating: 4.2,
    prep_time: 2,
    image: "f57",
  },
  {
    name: "7UP",
    category: "Cold Drink",
    cuisine_type: "Soft Drink",
    price: 49,
    is_veg: true,
    rating: 4.3,
    prep_time: 2,
    image: "f58",
  },
  {
    name: "Iced Tea",
    category: "Cold Drink",
    cuisine_type: "Soft Drink",
    price: 69,
    is_veg: true,
    rating: 4.4,
    prep_time: 3,
    image: "f59",
  },
  {
    name: "Blue Lagoon",
    category: "Cold Drink",
    cuisine_type: "Mocktail",
    price: 99,
    is_veg: true,
    rating: 4.4,
    prep_time: 4,
    image: "f60",
  },
  {
    name: "Strawberry Shake",
    category: "Cold Drink",
    cuisine_type: "Shake",
    price: 109,
    is_veg: true,
    rating: 4.5,
    prep_time: 5,
    image: "f61",
  },
];
